# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sampleIos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sampleIos

  target 'sampleIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sampleIosUITests' do
    # Pods for testing
  end

  pod 'sample', :path => '../sample'
end
